<a href="https://colab.research.google.com/github/kikiru328/enterprise_analysis/blob/main/M_New_clf_amt_ratio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Introduction  
>구매'액'비율 파생변수 생성

In [1]:
import os, sys
from google.colab import drive
drive.mount('/content/drive')
my_path = '/content/notebooks'
os.symlink('/content/drive/My Drive/Colab Notebooks', my_path)
sys.path.insert(0,my_path)

Mounted at /content/drive

In [2]:
#  Directory 변경 (모듈이용)
%pwd
%cd '../content/notebooks'

# module import
## Data Load
from pickle5 import pickle 

## Basic module
import pandas as pd
import numpy as np
import datetime as dt
import seaborn as sns
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

/content/drive/My Drive/Colab Notebooks

In [32]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/훈팡/새분류.pkl','rb') as file:
  df = pickle.load(file)

In [47]:
m1 = df[(df['구매년도']==2014)&(df['구매월']==1)]
m2 = df[(df['구매년도']==2014)&(df['구매월']==2)]
m3 = df[(df['구매년도']==2014)&(df['구매월']==3)]
m4 = df[(df['구매년도']==2014)&(df['구매월']==4)]
m5 = df[(df['구매년도']==2014)&(df['구매월']==5)]
m6 = df[(df['구매년도']==2014)&(df['구매월']==6)]
m7 = df[(df['구매년도']==2014)&(df['구매월']==7)]
m8 = df[(df['구매년도']==2014)&(df['구매월']==8)]
m9 = df[(df['구매년도']==2014)&(df['구매월']==9)]
m10 = df[(df['구매년도']==2014)&(df['구매월']==10)]
m11= df[(df['구매년도']==2014)&(df['구매월']==11)]
m12= df[(df['구매년도']==2014)&(df['구매월']==12)]

m13 = df[(df['구매년도']==2015)&(df['구매월']==1)]
m14 = df[(df['구매년도']==2015)&(df['구매월']==2)]
m15= df[(df['구매년도']==2015)&(df['구매월']==3)]
m16 = df[(df['구매년도']==2015)&(df['구매월']==4)]
m17 = df[(df['구매년도']==2015)&(df['구매월']==5)]
m18 = df[(df['구매년도']==2015)&(df['구매월']==6)]
m19 = df[(df['구매년도']==2015)&(df['구매월']==7)]
m20 = df[(df['구매년도']==2015)&(df['구매월']==8)]
m21 = df[(df['구매년도']==2015)&(df['구매월']==9)]
m22 = df[(df['구매년도']==2015)&(df['구매월']==10)]
m23 = df[(df['구매년도']==2015)&(df['구매월']==11)]
m24 = df[(df['구매년도']==2015)&(df['구매월']==12)]

In [48]:
df.새분류.unique()

array(['비내구재', '내구재', '준내구재', '사치품'], dtype=object)

In [49]:
def get_pivot(df):
  test = df.groupby(['고객번호','새분류']).sum().reset_index()
  pv = pd.pivot_table(test, index='고객번호',columns='새분류',values='구매금액')
  pv = pv.reset_index()
  pv = pv.fillna(0).astype(int)
  pv['total'] = pv[['내구재','준내구재','비내구재','사치품']].sum(axis=1)
  pv = pv.reset_index(drop=True).rename_axis(None, axis=1)
  pv = pv.set_index('고객번호')
  return pv

In [50]:
m1 = get_pivot(m1)
m2 = get_pivot(m2)
m3 = get_pivot(m3)
m4 = get_pivot(m4)
m5 = get_pivot(m5)
m6 = get_pivot(m6)
m7 = get_pivot(m7)
m8 = get_pivot(m8)
m9 = get_pivot(m9)
m10 = get_pivot(m10)
m11 = get_pivot(m11)
m12 = get_pivot(m12)
m13 = get_pivot(m13)
m14 = get_pivot(m14)
m15 = get_pivot(m15)
m16 = get_pivot(m16)
m17 = get_pivot(m17)
m18 = get_pivot(m18)
m19 = get_pivot(m19)
m20 = get_pivot(m20)
m21 = get_pivot(m21)
m22 = get_pivot(m22)
m23 = get_pivot(m23)
m24 = get_pivot(m24)

In [51]:
m1

          내구재     비내구재  사치품     준내구재    total
고객번호
1           0   554770    0  1752490  2307260
2      298150  2337870    0  1906270  4542290
3           0   128369    0        0   128369
4           0   223680    0   189520   413200
5           0  1155800    0    20000  1175800
...       ...      ...  ...      ...      ...
19318  299000   214580    0    10900   524480
19319       0   341360    0        0   341360
19320   13000   563790    0   141220   718010
19322       0   181686    0        0   181686
19325       0    70130    0        0    70130

[18647 rows x 5 columns]

In [52]:
def pr(df):
  Li = list(df.columns)
  for li in Li:
    df[f'{li}_amt_ratio'] = df[li] / df['total']
  df = df.drop(Li,axis=1)
  df = df.drop('total_amt_ratio',axis=1)
  df['amt_ratio_total'] = df.sum(axis=1)
  return df

In [53]:
m1 = pr(m1)
m2 = pr(m2)
m3 = pr(m3)
m4 = pr(m4)
m5 = pr(m5)
m6 = pr(m6)
m7 = pr(m7)
m8 = pr(m8)
m9 = pr(m9)
m10 = pr(m10)
m11 = pr(m11)
m12 = pr(m12)
m13 = pr(m13)
m14 = pr(m14)
m15 = pr(m15)
m16 = pr(m16)
m17 = pr(m17)
m18 = pr(m18)
m19 = pr(m19)
m20 = pr(m20)
m21 = pr(m21)
m22 = pr(m22)
m23 = pr(m23)
m24 = pr(m24)

In [54]:
m1

       내구재_amt_ratio  비내구재_amt_ratio  ...  준내구재_amt_ratio  amt_ratio_total
고객번호                                  ...
1           0.000000        0.240445  ...        0.759555              1.0
2           0.065639        0.514690  ...        0.419672              1.0
3           0.000000        1.000000  ...        0.000000              1.0
4           0.000000        0.541336  ...        0.458664              1.0
5           0.000000        0.982990  ...        0.017010              1.0
...              ...             ...  ...             ...              ...
19318       0.570088        0.409129  ...        0.020782              1.0
19319       0.000000        1.000000  ...        0.000000              1.0
19320       0.018106        0.785212  ...        0.196682              1.0
19322       0.000000        1.000000  ...        0.000000              1.0
19325       0.000000        1.000000  ...        0.000000              1.0

[18647 rows x 5 columns]

In [55]:
 def reName(a,df):
  cols = list(df.columns)
  for i in cols:
    df[f'{i}_{a}'] = df[i]
  A = df.drop(cols,axis=1)
  return A

In [56]:
m1 = reName(1,m1)
m2 = reName(2,m2)
m3 = reName(3,m3)
m4 = reName(4,m4)
m5 = reName(5,m5)
m6 = reName(6,m6)
m7 = reName(7,m7)
m8 = reName(8,m8)
m9 = reName(9,m9)
m10 = reName(10,m10)
m11 = reName(11,m11)
m12 = reName(12,m12)
m13 = reName(13,m13)
m14 = reName(14,m14)
m15 = reName(15,m15)
m16 = reName(16,m16)
m17 = reName(17,m17)
m18 = reName(18,m18)
m19 = reName(19,m19)
m20 = reName(20,m20)
m21 = reName(21,m21)
m22 = reName(22,m22)
m23 = reName(23,m23)
m24 = reName(24,m24)

In [57]:
a = df[['고객번호','구매금액']]
a = a.groupby('고객번호').sum()
a = a.reset_index()
train_bin = a[['고객번호']]
train_bin

        고객번호
0          1
1          2
2          3
3          4
4          5
...      ...
19080  19356
19081  19357
19082  19359
19083  19360
19084  19364

[19085 rows x 1 columns]

In [58]:
m1

       내구재_amt_ratio_1  비내구재_amt_ratio_1  ...  준내구재_amt_ratio_1  amt_ratio_total_1
고객번호                                      ...
1             0.000000          0.240445  ...          0.759555                1.0
2             0.065639          0.514690  ...          0.419672                1.0
3             0.000000          1.000000  ...          0.000000                1.0
4             0.000000          0.541336  ...          0.458664                1.0
5             0.000000          0.982990  ...          0.017010                1.0
...                ...               ...  ...               ...                ...
19318         0.570088          0.409129  ...          0.020782                1.0
19319         0.000000          1.000000  ...          0.000000                1.0
19320         0.018106          0.785212  ...          0.196682                1.0
19322         0.000000          1.000000  ...          0.000000                1.0
19325         0.000000          1.000000  ...          0.000000                1.0

[18647 rows x 5 columns]

In [59]:
trainL = [m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12]
testL = [m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,m16,m17,m18]

In [60]:
m1

       내구재_amt_ratio_1  비내구재_amt_ratio_1  ...  준내구재_amt_ratio_1  amt_ratio_total_1
고객번호                                      ...
1             0.000000          0.240445  ...          0.759555                1.0
2             0.065639          0.514690  ...          0.419672                1.0
3             0.000000          1.000000  ...          0.000000                1.0
4             0.000000          0.541336  ...          0.458664                1.0
5             0.000000          0.982990  ...          0.017010                1.0
...                ...               ...  ...               ...                ...
19318         0.570088          0.409129  ...          0.020782                1.0
19319         0.000000          1.000000  ...          0.000000                1.0
19320         0.018106          0.785212  ...          0.196682                1.0
19322         0.000000          1.000000  ...          0.000000                1.0
19325         0.000000          1.000000  ...          0.000000                1.0

[18647 rows x 5 columns]

In [61]:
def new_train_df(A):
  global train_bin
  for i in A:
    train_bin = pd.merge(train_bin,i,on='고객번호',how='left')
  return train_bin

In [62]:
train = new_train_df(trainL)
train = train.fillna(0)
train

        고객번호  내구재_amt_ratio_1  ...  준내구재_amt_ratio_12  amt_ratio_total_12
0          1         0.000000  ...           0.671773                 1.0
1          2         0.065639  ...           0.049927                 1.0
2          3         0.000000  ...           0.000000                 1.0
3          4         0.000000  ...           0.345832                 1.0
4          5         0.000000  ...           0.000000                 1.0
...      ...              ...  ...                ...                 ...
19080  19356         0.000000  ...           0.000000                 1.0
19081  19357         0.000000  ...           0.224171                 1.0
19082  19359         0.000000  ...           0.000000                 1.0
19083  19360         0.000000  ...           0.043500                 1.0
19084  19364         0.000000  ...           0.235453                 1.0

[19085 rows x 61 columns]

In [63]:
col_standard =  df[(df['구매년도']==2014)&(df['구매월']==1)]
col_standard = get_pivot(col_standard)
col_standard = pr(col_standard)
col_standard = list(col_standard.columns)
col_standard

['내구재_amt_ratio',
 '비내구재_amt_ratio',
 '사치품_amt_ratio',
 '준내구재_amt_ratio',
 'amt_ratio_total']

In [67]:
trainlist =list(range(1,13))
col_standard


trainList = []
for col in col_standard:
  for h in trainlist:
    trainList.append(f'{col}_{h}')

trainList = ['고객번호','내구재_amt_ratio_1',
 '내구재_amt_ratio_2',
 '내구재_amt_ratio_3',
 '내구재_amt_ratio_4',
 '내구재_amt_ratio_5',
 '내구재_amt_ratio_6',
 '내구재_amt_ratio_7',
 '내구재_amt_ratio_8',
 '내구재_amt_ratio_9',
 '내구재_amt_ratio_10',
 '내구재_amt_ratio_11',
 '내구재_amt_ratio_12',
 '준내구재_amt_ratio_1',
 '준내구재_amt_ratio_2',
 '준내구재_amt_ratio_3',
 '준내구재_amt_ratio_4',
 '준내구재_amt_ratio_5',
 '준내구재_amt_ratio_6',
 '준내구재_amt_ratio_7',
 '준내구재_amt_ratio_8',
 '준내구재_amt_ratio_9',
 '준내구재_amt_ratio_10',
 '준내구재_amt_ratio_11',
 '준내구재_amt_ratio_12',
 '비내구재_amt_ratio_1',
 '비내구재_amt_ratio_2',
 '비내구재_amt_ratio_3',
 '비내구재_amt_ratio_4',
 '비내구재_amt_ratio_5',
 '비내구재_amt_ratio_6',
 '비내구재_amt_ratio_7',
 '비내구재_amt_ratio_8',
 '비내구재_amt_ratio_9',
 '비내구재_amt_ratio_10',
 '비내구재_amt_ratio_11',
 '비내구재_amt_ratio_12',
 '사치품_amt_ratio_1',
 '사치품_amt_ratio_2',
 '사치품_amt_ratio_3',
 '사치품_amt_ratio_4',
 '사치품_amt_ratio_5',
 '사치품_amt_ratio_6',
 '사치품_amt_ratio_7',
 '사치품_amt_ratio_8',
 '사치품_amt_ratio_9',
 '사치품_amt_ratio_10',
 '사치품_amt_ratio_11',
 '사치품_amt_ratio_12'
]
train = train[trainList]
train

        고객번호  내구재_amt_ratio_1  ...  사치품_amt_ratio_11  사치품_amt_ratio_12
0          1         0.000000  ...          0.000000          0.000000
1          2         0.065639  ...          0.163142          0.000000
2          3         0.000000  ...          0.000000          0.000000
3          4         0.000000  ...          0.000000          0.000000
4          5         0.000000  ...          0.000000          0.000000
...      ...              ...  ...               ...               ...
19080  19356         0.000000  ...          0.000000          0.000000
19081  19357         0.000000  ...          0.000000          0.000000
19082  19359         0.000000  ...          0.000000          0.000000
19083  19360         0.000000  ...          0.000000          0.000000
19084  19364         0.000000  ...          0.000000          0.395394

[19085 rows x 49 columns]

In [70]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/1012발표도못하고수정/월별/train/m_new_amt_ratio.pkl','wb') as train_save:
  pickle.dump(train,train_save)

In [71]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/1012발표도못하고수정/월별/train/m_new_amt_ratio.pkl','rb') as train_save:
  check = pickle.load(train_save)
check

        고객번호  내구재_amt_ratio_1  ...  사치품_amt_ratio_11  사치품_amt_ratio_12
0          1         0.000000  ...          0.000000          0.000000
1          2         0.065639  ...          0.163142          0.000000
2          3         0.000000  ...          0.000000          0.000000
3          4         0.000000  ...          0.000000          0.000000
4          5         0.000000  ...          0.000000          0.000000
...      ...              ...  ...               ...               ...
19080  19356         0.000000  ...          0.000000          0.000000
19081  19357         0.000000  ...          0.000000          0.000000
19082  19359         0.000000  ...          0.000000          0.000000
19083  19360         0.000000  ...          0.000000          0.000000
19084  19364         0.000000  ...          0.000000          0.395394

[19085 rows x 49 columns]

In [72]:
testL = [m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15,m16,m17,m18]

In [73]:
def new_test_df(A):
  global train_bin
  for i in A:
    train_bin = pd.merge(train_bin,i,on='고객번호',how='left')
  return train_bin

In [74]:
a = df[['고객번호','구매금액']]
a = a.groupby('고객번호').sum()
a = a.reset_index()
train_bin = a[['고객번호']]
train_bin

        고객번호
0          1
1          2
2          3
3          4
4          5
...      ...
19080  19356
19081  19357
19082  19359
19083  19360
19084  19364

[19085 rows x 1 columns]

In [75]:
test = new_test_df(testL)
test = test.fillna(0)
test

        고객번호  내구재_amt_ratio_1  ...  준내구재_amt_ratio_18  amt_ratio_total_18
0          1         0.000000  ...           0.687317                 1.0
1          2         0.065639  ...           0.353437                 1.0
2          3         0.000000  ...           0.000000                 1.0
3          4         0.000000  ...           0.432905                 1.0
4          5         0.000000  ...           0.000000                 0.0
...      ...              ...  ...                ...                 ...
19080  19356         0.000000  ...           0.000000                 1.0
19081  19357         0.000000  ...           0.000000                 1.0
19082  19359         0.000000  ...           0.000000                 1.0
19083  19360         0.000000  ...           0.000000                 1.0
19084  19364         0.000000  ...           0.124241                 1.0

[19085 rows x 91 columns]

In [77]:
testlist = list(range(1,19))
c_li = col_standard

testList = []
for col in col_standard:
  for h in testlist:
    testList.append(f'{col}_{h}')
testList =['고객번호','내구재_amt_ratio_1',
 '내구재_amt_ratio_2',
 '내구재_amt_ratio_3',
 '내구재_amt_ratio_4',
 '내구재_amt_ratio_5',
 '내구재_amt_ratio_6',
 '내구재_amt_ratio_7',
 '내구재_amt_ratio_8',
 '내구재_amt_ratio_9',
 '내구재_amt_ratio_10',
 '내구재_amt_ratio_11',
 '내구재_amt_ratio_12',
 '내구재_amt_ratio_13',
 '내구재_amt_ratio_14',
 '내구재_amt_ratio_15',
 '내구재_amt_ratio_16',
 '내구재_amt_ratio_17',
 '내구재_amt_ratio_18',
 '준내구재_amt_ratio_1',
 '준내구재_amt_ratio_2',
 '준내구재_amt_ratio_3',
 '준내구재_amt_ratio_4',
 '준내구재_amt_ratio_5',
 '준내구재_amt_ratio_6',
 '준내구재_amt_ratio_7',
 '준내구재_amt_ratio_8',
 '준내구재_amt_ratio_9',
 '준내구재_amt_ratio_10',
 '준내구재_amt_ratio_11',
 '준내구재_amt_ratio_12',
 '준내구재_amt_ratio_13',
 '준내구재_amt_ratio_14',
 '준내구재_amt_ratio_15',
 '준내구재_amt_ratio_16',
 '준내구재_amt_ratio_17',
 '준내구재_amt_ratio_18',
 '비내구재_amt_ratio_1',
 '비내구재_amt_ratio_2',
 '비내구재_amt_ratio_3',
 '비내구재_amt_ratio_4',
 '비내구재_amt_ratio_5',
 '비내구재_amt_ratio_6',
 '비내구재_amt_ratio_7',
 '비내구재_amt_ratio_8',
 '비내구재_amt_ratio_9',
 '비내구재_amt_ratio_10',
 '비내구재_amt_ratio_11',
 '비내구재_amt_ratio_12',
 '비내구재_amt_ratio_13',
 '비내구재_amt_ratio_14',
 '비내구재_amt_ratio_15',
 '비내구재_amt_ratio_16',
 '비내구재_amt_ratio_17',
 '비내구재_amt_ratio_18',
 '사치품_amt_ratio_1',
 '사치품_amt_ratio_2',
 '사치품_amt_ratio_3',
 '사치품_amt_ratio_4',
 '사치품_amt_ratio_5',
 '사치품_amt_ratio_6',
 '사치품_amt_ratio_7',
 '사치품_amt_ratio_8',
 '사치품_amt_ratio_9',
 '사치품_amt_ratio_10',
 '사치품_amt_ratio_11',
 '사치품_amt_ratio_12',
 '사치품_amt_ratio_13',
 '사치품_amt_ratio_14',
 '사치품_amt_ratio_15',
 '사치품_amt_ratio_16',
 '사치품_amt_ratio_17',
 '사치품_amt_ratio_18',
]
test = test[testList]
test

        고객번호  내구재_amt_ratio_1  ...  사치품_amt_ratio_17  사치품_amt_ratio_18
0          1         0.000000  ...               0.0               0.0
1          2         0.065639  ...               0.0               0.0
2          3         0.000000  ...               0.0               0.0
3          4         0.000000  ...               0.0               0.0
4          5         0.000000  ...               0.0               0.0
...      ...              ...  ...               ...               ...
19080  19356         0.000000  ...               0.0               0.0
19081  19357         0.000000  ...               0.0               0.0
19082  19359         0.000000  ...               0.0               0.0
19083  19360         0.000000  ...               0.0               0.0
19084  19364         0.000000  ...               0.0               0.0

[19085 rows x 73 columns]

In [78]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/1012발표도못하고수정/월별/test/m_new_amt_ratio.pkl','wb') as test_save:
  pickle.dump(test,test_save)

In [79]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/1012발표도못하고수정/월별/test/m_new_amt_ratio.pkl','rb') as test_save:
  check = pickle.load(test_save)
check

        고객번호  내구재_amt_ratio_1  ...  사치품_amt_ratio_17  사치품_amt_ratio_18
0          1         0.000000  ...               0.0               0.0
1          2         0.065639  ...               0.0               0.0
2          3         0.000000  ...               0.0               0.0
3          4         0.000000  ...               0.0               0.0
4          5         0.000000  ...               0.0               0.0
...      ...              ...  ...               ...               ...
19080  19356         0.000000  ...               0.0               0.0
19081  19357         0.000000  ...               0.0               0.0
19082  19359         0.000000  ...               0.0               0.0
19083  19360         0.000000  ...               0.0               0.0
19084  19364         0.000000  ...               0.0               0.0

[19085 rows x 73 columns]

In [ ]:
d

In [ ]:
trainlist = ['H1','H2']
c_li = list(pr1.columns)


trainList = []
for c in c_li:
  for t in trainlist:
    trainList.append(f'{t}_{c}')

In [ ]:
trainList = ['H1_내구재_amt_ratio',
 'H2_내구재_amt_ratio',
 'H1_준내구재_amt_ratio',
 'H2_준내구재_amt_ratio',
 'H1_비내구재_amt_ratio',
 'H2_비내구재_amt_ratio',
 'H1_사치품_amt_ratio',
 'H2_사치품_amt_ratio']

In [ ]:
train = train[trainList]

In [ ]:
train = train.reset_index()
train

        고객번호  H1_내구재_amt_ratio  ...  H1_사치품_amt_ratio  H2_사치품_amt_ratio
0          1          0.008916  ...          0.000000          0.000000
1          2          0.080269  ...          0.000000          0.019804
2          3          0.000000  ...          0.000000          0.000000
3          4          0.000000  ...          0.000000          0.000000
4          5          0.009139  ...          0.010439          0.000000
...      ...               ...  ...               ...               ...
19080  19356          0.000000  ...          0.000000          0.000000
19081  19357          0.000000  ...          0.000000          0.002987
19082  19359          0.000000  ...          0.000000          0.000000
19083  19360          0.000000  ...          0.000000          0.000000
19084  19364          0.000000  ...          0.000000          0.200493

[19085 rows x 9 columns]

In [ ]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/1012발표도못하고수정/10월14일이후 새로추가/train/new_pur_ratio.pkl','wb') as train_save:
  pickle.dump(train,train_save)

In [ ]:
def new_test_df(a,b,c):
    A = pd.concat([a,b],axis=1)
    train = pd.concat([A,c],axis=1)    
    return train

test = new_test_df(H1,H2,H3)

In [ ]:
testlist = ['H1','H2','H3']
c_li = list(pr1.columns)

testList = []
for col in c_li:
  for h in testlist:
    testList.append(f'{h}_{col}')

In [ ]:
testList=['H1_내구재_amt_ratio',
 'H2_내구재_amt_ratio',
 'H3_내구재_amt_ratio',
 'H1_비내구재_amt_ratio',
 'H2_비내구재_amt_ratio',
 'H3_비내구재_amt_ratio',
 'H1_사치품_amt_ratio',
 'H2_사치품_amt_ratio',
 'H3_사치품_amt_ratio',
 'H1_준내구재_amt_ratio',
 'H2_준내구재_amt_ratio',
 'H3_준내구재_amt_ratio']

test = test[testList]
test = test.reset_index()
test

        고객번호  H1_내구재_amt_ratio  ...  H2_준내구재_amt_ratio  H3_준내구재_amt_ratio
0          1          0.008916  ...           0.464163           0.716498
1          2          0.080269  ...           0.573290           0.489636
2          3          0.000000  ...           0.004796           0.000000
3          4          0.000000  ...           0.543109           0.422712
4          5          0.009139  ...           0.149704           0.157551
...      ...               ...  ...                ...                ...
19080  19356          0.000000  ...           0.000000           0.000000
19081  19357          0.000000  ...           0.357643           0.253765
19082  19359          0.000000  ...           0.000000           0.000000
19083  19360          0.000000  ...           0.019320           0.122438
19084  19364          0.000000  ...           0.180577           0.049967

[19085 rows x 13 columns]

In [ ]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/1012발표도못하고수정/10월14일이후 새로추가/test/new_pur_ratio.pkl','wb') as test_save:
  pickle.dump(test,test_save)

In [ ]:
def ratio(df):
  test = df[['고객번호','새분류']]
  test = test.set_index('고객번호')
  A = pd.get_dummies(test['새분류']).reset_index()
  A = A.groupby('고객번호').sum().astype(int)
  Li = list(A.columns)
  A['total'] = A.sum(axis=1).astype(int)
  for i in Li:
    A[f"{i}_r"] = A[i] / A['total']
  B = A.drop(['내구재','사치품','비내구재','준내구재','total'],axis=1)
  B['total_r'] = B.sum(axis=1)
  return B

In [ ]:
H1_r = ratio(df_1)
H2_r = ratio(df_2)
H3_r = ratio(df_3)
H4_r = ratio(df_4)

In [ ]:
H1_r

          내구재_r    비내구재_r     사치품_r    준내구재_r  total_r
고객번호
1      0.004202  0.693277  0.000000  0.302521      1.0
2      0.032448  0.823009  0.000000  0.144543      1.0
3      0.000000  0.997126  0.000000  0.002874      1.0
4      0.000000  0.851852  0.000000  0.148148      1.0
5      0.002653  0.952255  0.002653  0.042440      1.0
...         ...       ...       ...       ...      ...
19356  0.000000  1.000000  0.000000  0.000000      1.0
19357  0.000000  0.750000  0.000000  0.250000      1.0
19359  0.000000  1.000000  0.000000  0.000000      1.0
19360  0.000000  1.000000  0.000000  0.000000      1.0
19364  0.000000  0.968085  0.000000  0.031915      1.0

[19085 rows x 5 columns]

In [ ]:
def reName(a,df):
    cols = list(df.columns)
    for i in cols:
      df[f'{a}_{i}'] = df[i]
    A = df.drop(cols,axis=1)
    return A

H1 = reName('H1',H1_r)
H2 = reName('H2',H2_r)
H3 = reName('H3',H3_r)
H4 = reName('H4',H4_r)

In [ ]:
H1

       H1_내구재_r  H1_비내구재_r  H1_사치품_r  H1_준내구재_r  H1_total_r
고객번호
1      0.004202   0.693277  0.000000   0.302521         1.0
2      0.032448   0.823009  0.000000   0.144543         1.0
3      0.000000   0.997126  0.000000   0.002874         1.0
4      0.000000   0.851852  0.000000   0.148148         1.0
5      0.002653   0.952255  0.002653   0.042440         1.0
...         ...        ...       ...        ...         ...
19356  0.000000   1.000000  0.000000   0.000000         1.0
19357  0.000000   0.750000  0.000000   0.250000         1.0
19359  0.000000   1.000000  0.000000   0.000000         1.0
19360  0.000000   1.000000  0.000000   0.000000         1.0
19364  0.000000   0.968085  0.000000   0.031915         1.0

[19085 rows x 5 columns]

In [ ]:
def new_train_df(a,b):
    A = pd.concat([a,b],axis=1)
    return A

train = new_train_df(H1,H2)

In [ ]:
train

       H1_내구재_r  H1_비내구재_r  H1_사치품_r  ...  H2_사치품_r  H2_준내구재_r  H2_total_r
고객번호                                  ...
1      0.004202   0.693277  0.000000  ...  0.000000   0.221910         1.0
2      0.032448   0.823009  0.000000  ...  0.003690   0.169742         1.0
3      0.000000   0.997126  0.000000  ...  0.000000   0.002558         1.0
4      0.000000   0.851852  0.000000  ...  0.000000   0.215116         1.0
5      0.002653   0.952255  0.002653  ...  0.000000   0.038462         1.0
...         ...        ...       ...  ...       ...        ...         ...
19356  0.000000   1.000000  0.000000  ...  0.000000   0.000000         1.0
19357  0.000000   0.750000  0.000000  ...  0.002353   0.056471         1.0
19359  0.000000   1.000000  0.000000  ...  0.000000   0.000000         1.0
19360  0.000000   1.000000  0.000000  ...  0.000000   0.011070         1.0
19364  0.000000   0.968085  0.000000  ...  0.003650   0.018248         1.0

[19085 rows x 10 columns]

In [ ]:
# trainlist = ['H1','H2','H3']
# c_li = list(H1_r.columns)


# trainList = []
# for col in c_li:
#   for h in trainlist:
#     trainList.append(f'{h}_{col}')

# train = train[trainList]

train = train[['H1_내구재_r',
 'H2_내구재_r',
 'H1_준내구재_r',
 'H2_준내구재_r',
  'H1_비내구재_r',
 'H2_비내구재_r',
 'H1_사치품_r',
 'H2_사치품_r',
]]
# trainList

In [ ]:
train = train.reset_index()
train

        고객번호  H1_내구재_r  H2_내구재_r  ...  H2_비내구재_r  H1_사치품_r  H2_사치품_r
0          1  0.004202  0.061798  ...   0.716292  0.000000  0.000000
1          2  0.032448  0.011070  ...   0.815498  0.000000  0.003690
2          3  0.000000  0.000000  ...   0.997442  0.000000  0.000000
3          4  0.000000  0.023256  ...   0.761628  0.000000  0.000000
4          5  0.002653  0.015385  ...   0.946154  0.002653  0.000000
...      ...       ...       ...  ...        ...       ...       ...
19080  19356  0.000000  0.002625  ...   0.997375  0.000000  0.000000
19081  19357  0.000000  0.000000  ...   0.941176  0.000000  0.002353
19082  19359  0.000000  0.000000  ...   1.000000  0.000000  0.000000
19083  19360  0.000000  0.000000  ...   0.988930  0.000000  0.000000
19084  19364  0.000000  0.000000  ...   0.978102  0.000000  0.003650

[19085 rows x 9 columns]

In [ ]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/1012발표도못하고수정/10월14일이후 새로추가/train/new_ratio.pkl','wb') as train_save:
  pickle.dump(train,train_save)

In [ ]:
def new_test_df(a,b,c):
    A = pd.concat([a,b],axis=1)
    train = pd.concat([A,c],axis=1)    
    return train

test = new_test_df(H1,H2,H3)

In [ ]:
test

       H1_내구재_r  H1_비내구재_r  H1_사치품_r  ...  H3_사치품_r  H3_준내구재_r  H3_total_r
고객번호                                  ...
1      0.004202   0.693277  0.000000  ...  0.003205   0.233974         1.0
2      0.032448   0.823009  0.000000  ...  0.015326   0.214559         1.0
3      0.000000   0.997126  0.000000  ...  0.000000   0.000000         1.0
4      0.000000   0.851852  0.000000  ...  0.000000   0.091255         1.0
5      0.002653   0.952255  0.002653  ...  0.000000   0.008130         1.0
...         ...        ...       ...  ...       ...        ...         ...
19356  0.000000   1.000000  0.000000  ...  0.000000   0.000000         1.0
19357  0.000000   0.750000  0.000000  ...  0.002208   0.030905         1.0
19359  0.000000   1.000000  0.000000  ...  0.000000   0.000000         1.0
19360  0.000000   1.000000  0.000000  ...  0.006579   0.026316         1.0
19364  0.000000   0.968085  0.000000  ...  0.000000   0.011811         1.0

[19085 rows x 15 columns]

In [ ]:
# testlist = ['H1','H2','H3','H4']
# c_li = list(H1_r.columns)

# testList = []
# for col in c_li:
#   for h in testlist:
#     testList.append(f'{h}_{col}')
# test = test[testList]

test = test[['H1_내구재_r',
 'H2_내구재_r',
 'H3_내구재_r',
 'H1_준내구재_r',
 'H2_준내구재_r',
 'H3_준내구재_r',
 'H1_비내구재_r',
 'H2_비내구재_r',
 'H3_비내구재_r',
 'H1_사치품_r',
 'H2_사치품_r',
 'H3_사치품_r'
]]
test = test.reset_index()
test

        고객번호  H1_내구재_r  H2_내구재_r  ...  H1_사치품_r  H2_사치품_r  H3_사치품_r
0          1  0.004202  0.061798  ...  0.000000  0.000000  0.003205
1          2  0.032448  0.011070  ...  0.000000  0.003690  0.015326
2          3  0.000000  0.000000  ...  0.000000  0.000000  0.000000
3          4  0.000000  0.023256  ...  0.000000  0.000000  0.000000
4          5  0.002653  0.015385  ...  0.002653  0.000000  0.000000
...      ...       ...       ...  ...       ...       ...       ...
19080  19356  0.000000  0.002625  ...  0.000000  0.000000  0.000000
19081  19357  0.000000  0.000000  ...  0.000000  0.002353  0.002208
19082  19359  0.000000  0.000000  ...  0.000000  0.000000  0.000000
19083  19360  0.000000  0.000000  ...  0.000000  0.000000  0.006579
19084  19364  0.000000  0.000000  ...  0.000000  0.003650  0.000000

[19085 rows x 13 columns]

In [ ]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/1012발표도못하고수정/10월14일이후 새로추가/test/new_ratio.pkl','wb') as test_save:
  pickle.dump(test,test_save)