<a href="https://colab.research.google.com/github/kikiru328/enterprise_analysis/blob/main/B_clf_ratio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Introduction  
>대분류별 구매량 비율

In [1]:
import os, sys
from google.colab import drive
drive.mount('/content/drive')
my_path = '/content/notebooks'
os.symlink('/content/drive/My Drive/Colab Notebooks', my_path)
sys.path.insert(0,my_path)

Mounted at /content/drive

In [2]:
#  Directory 변경 (모듈이용)
%pwd
%cd '../content/notebooks'

# module import
## Data Load
from pickle5 import pickle 

## Basic module
import pandas as pd
import numpy as np
import datetime as dt
import seaborn as sns
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

/content/drive/My Drive/Colab Notebooks

In [3]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/data/EDA/기존_purprd_cust.pkl','rb') as file:
  df = pickle.load(file)

In [4]:
df

         성별    연령대    거주지역 제휴사  멤버십가입개수  ...  구매시간     대분류명   중분류명    소분류명   구매금액
0         F    50대  경기 김포시   A        0  ...    20  가구/인테리어   일용잡화    위생세제   1000
1         F    50대  경기 김포시   A        0  ...    20     가공식품   가공식품  일반가공식품   4100
2         F  60세이상  경기 김포시   A        0  ...    12     신선식품    농산물      채소   5000
3         F  60세이상  경기 김포시   A        0  ...    12     가공식품  젓갈/반찬    벌크김치  10200
4         F    50대  경기 김포시   A        0  ...    13  가구/인테리어   일용잡화    위생세제   3950
...      ..    ...     ...  ..      ...  ...   ...      ...    ...     ...    ...
28593025  M    30대  경기 김포시   D        1  ...    13     가공식품     음료   일반차음료   3000
28593026  M    30대  경기 김포시   D        1  ...    13     가공식품     음료    커피음료   1300
28593027  M    50대   울산 동구   D        0  ...    16     일상용품   헤어케어      샴푸  59700
28593028  M    30대  경기 김포시   D        1  ...    23     가공식품     과자    하드캔디   2000
28593029  M    30대  서울 동작구   D        1  ...    22     가공식품     과자      쿠키   2500

[28445983 rows x 16 columns]

In [90]:
df_1 = df[(df['구매년도']==2014)&(df['구매월']>=1) & (df['구매월']<=6)] 
df_2 = df[(df['구매년도']==2014)&(df['구매월']>=7) & (df['구매월']<=12)]
df_3 = df[(df['구매년도']==2015)&(df['구매월']>=1) & (df['구매월']<=6)]
df_4 = df[(df['구매년도']==2015)&(df['구매월']>=7) & (df['구매월']<=12)]

In [91]:
t = pd.get_dummies(df_1['대분류명'])
print(t.shape)
df_1.shape

(6704092, 11)

(6704092, 16)

In [95]:
def ratio(df):
  test = df[['고객번호','대분류명']]
  test = test.set_index('고객번호')
  A = pd.get_dummies(test['대분류명']).reset_index()
  A = A.groupby('고객번호').sum().astype(int)
  Li = list(A.columns)
  A['total'] = A.sum(axis=1).astype(int)
  for i in Li:
    A[f"{i}_r"] = A[i] / A['total']
  B = A.drop(['가공식품', '가구/인테리어', '교육/문화용품', '기타', '디지털/가전', '명품', '신선식품', '의류',
    '일상용품', '전문스포츠/레저', '패션잡화','total'],axis=1)
  return B

In [109]:
H1_r = ratio(df_1)
H2_r = ratio(df_2)
H3_r = ratio(df_3)
H4_r = ratio(df_4)

In [110]:
H1_r

         가공식품_r  가구/인테리어_r  교육/문화용품_r  ...    일상용품_r  전문스포츠/레저_r    패션잡화_r
고객번호                                   ...
1      0.277311   0.037815        0.0  ...  0.100840    0.046218  0.071429
2      0.141593   0.091445        0.0  ...  0.070796    0.032448  0.047198
3      0.681034   0.000000        0.0  ...  0.129310    0.000000  0.000000
4      0.333333   0.025926        0.0  ...  0.062963    0.011111  0.029630
5      0.320955   0.074271        0.0  ...  0.015915    0.002653  0.015915
...         ...        ...        ...  ...       ...         ...       ...
19356  0.617021   0.000000        0.0  ...  0.042553    0.000000  0.000000
19357  0.583333   0.000000        0.0  ...  0.000000    0.000000  0.000000
19359  0.647059   0.000000        0.0  ...  0.058824    0.000000  0.000000
19360  0.487805   0.000000        0.0  ...  0.512195    0.000000  0.000000
19364  0.095745   0.000000        0.0  ...  0.872340    0.031915  0.000000

[19085 rows x 11 columns]

In [98]:
def reName(a,df):
    cols = list(df.columns)
    for i in cols:
      df[f'{a}_{i}'] = df[i]
    A = df.drop(cols,axis=1)
    return A

H1 = reName('H1',H1_r)
H2 = reName('H2',H2_r)
H3 = reName('H3',H3_r)
H4 = reName('H4',H4_r)

In [99]:
H1

       H1_가공식품_r  H1_가구/인테리어_r  ...  H1_전문스포츠/레저_r  H1_패션잡화_r
고객번호                            ...
1       0.277311      0.037815  ...       0.046218   0.071429
2       0.141593      0.091445  ...       0.032448   0.047198
3       0.681034      0.000000  ...       0.000000   0.000000
4       0.333333      0.025926  ...       0.011111   0.029630
5       0.320955      0.074271  ...       0.002653   0.015915
...          ...           ...  ...            ...        ...
19356   0.617021      0.000000  ...       0.000000   0.000000
19357   0.583333      0.000000  ...       0.000000   0.000000
19359   0.647059      0.000000  ...       0.000000   0.000000
19360   0.487805      0.000000  ...       0.000000   0.000000
19364   0.095745      0.000000  ...       0.031915   0.000000

[19085 rows x 11 columns]

In [100]:
def train_df(a,b,c):
    A = pd.concat([a,b],axis=1)
    train = pd.concat([A,c],axis=1)
    return train

train = train_df(H1,H2,H3)

In [101]:
train

       H1_가공식품_r  H1_가구/인테리어_r  ...  H3_전문스포츠/레저_r  H3_패션잡화_r
고객번호                            ...
1       0.277311      0.037815  ...       0.016026   0.041667
2       0.141593      0.091445  ...       0.026820   0.053640
3       0.681034      0.000000  ...       0.000000   0.000000
4       0.333333      0.025926  ...       0.007605   0.015209
5       0.320955      0.074271  ...       0.000000   0.000000
...          ...           ...  ...            ...        ...
19356   0.617021      0.000000  ...       0.000000   0.000000
19357   0.583333      0.000000  ...       0.002208   0.008830
19359   0.647059      0.000000  ...       0.000000   0.000000
19360   0.487805      0.000000  ...       0.006579   0.013158
19364   0.095745      0.000000  ...       0.000000   0.007874

[19085 rows x 33 columns]

In [116]:
trainlist = ['H1','H2','H3']
c_li = list(H1_r.columns)


trainList = []
for col in c_li:
  for h in trainlist:
    trainList.append(f'{h}_{col}')

train = train[trainList]

train

       H1_가공식품_r  H2_가공식품_r  H3_가공식품_r  ...  H1_패션잡화_r  H2_패션잡화_r  H3_패션잡화_r
고객번호                                    ...
1       0.277311   0.308989   0.333333  ...   0.071429   0.030899   0.041667
2       0.141593   0.236162   0.149425  ...   0.047198   0.025830   0.053640
3       0.681034   0.672634   0.704545  ...   0.000000   0.000000   0.000000
4       0.333333   0.319767   0.349810  ...   0.029630   0.034884   0.015209
5       0.320955   0.292308   0.382114  ...   0.015915   0.015385   0.000000
...          ...        ...        ...  ...        ...        ...        ...
19356   0.617021   0.706037   0.654378  ...   0.000000   0.000000   0.000000
19357   0.583333   0.710588   0.684327  ...   0.000000   0.007059   0.008830
19359   0.647059   0.713483   0.779126  ...   0.000000   0.000000   0.000000
19360   0.487805   0.428044   0.506579  ...   0.000000   0.000000   0.013158
19364   0.095745   0.251825   0.208661  ...   0.000000   0.007299   0.007874

[19085 rows x 33 columns]

In [126]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/진짜진짜최종/123(train)/분류_r_123.pkl','wb') as train_save:
  pickle.dump(train,train_save)

In [102]:
def test_df(a,b,c,d):
    A = pd.concat([a,b],axis=1)
    train = pd.concat([A,c],axis=1)
    test = pd.concat([train,d],axis=1)
    return test

test = test_df(H1,H2,H3,H4)

In [103]:
test

       H1_가공식품_r  H1_가구/인테리어_r  ...  H4_전문스포츠/레저_r  H4_패션잡화_r
고객번호                            ...
1       0.277311      0.037815  ...       0.019868   0.052980
2       0.141593      0.091445  ...       0.012245   0.048980
3       0.681034      0.000000  ...       0.000000   0.000000
4       0.333333      0.025926  ...       0.008889   0.017778
5       0.320955      0.074271  ...       0.000000   0.011236
...          ...           ...  ...            ...        ...
19356   0.617021      0.000000  ...       0.002404   0.000000
19357   0.583333      0.000000  ...       0.005848   0.005848
19359   0.647059      0.000000  ...       0.000000   0.000000
19360   0.487805      0.000000  ...       0.000000   0.012500
19364   0.095745      0.000000  ...       0.004854   0.000000

[19085 rows x 44 columns]

In [117]:
testlist = ['H1','H2','H3','H4']
c_li = list(H1_r.columns)

testList = []
for col in c_li:
  for h in testlist:
    testList.append(f'{h}_{col}')
test = test[testList]

test

       H1_가공식품_r  H2_가공식품_r  H3_가공식품_r  ...  H2_패션잡화_r  H3_패션잡화_r  H4_패션잡화_r
고객번호                                    ...
1       0.277311   0.308989   0.333333  ...   0.030899   0.041667   0.052980
2       0.141593   0.236162   0.149425  ...   0.025830   0.053640   0.048980
3       0.681034   0.672634   0.704545  ...   0.000000   0.000000   0.000000
4       0.333333   0.319767   0.349810  ...   0.034884   0.015209   0.017778
5       0.320955   0.292308   0.382114  ...   0.015385   0.000000   0.011236
...          ...        ...        ...  ...        ...        ...        ...
19356   0.617021   0.706037   0.654378  ...   0.000000   0.000000   0.000000
19357   0.583333   0.710588   0.684327  ...   0.007059   0.008830   0.005848
19359   0.647059   0.713483   0.779126  ...   0.000000   0.000000   0.000000
19360   0.487805   0.428044   0.506579  ...   0.000000   0.013158   0.012500
19364   0.095745   0.251825   0.208661  ...   0.007299   0.007874   0.000000

[19085 rows x 44 columns]

In [128]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/진짜진짜최종/4(test)/분류_r_1234.pkl','wb') as test_save:
  pickle.dump(test,test_save)